version: '3.1'

services: 
  phpmyadmin:
    image: phpmyadmin:5.1.1-apache
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      


  wordpress:
    image: wordpress:5.7.2-php7.4-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usuario
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpress-db
    volumes:
      - wordpress:/var/www/html
      

  db:
    image: mariadb:10.6.3-focal
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress:
  mariadb: