version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usuario
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpress-db
    volumes:
      - wordpress:/var/www/html
      

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress:
  mariadb: